### PR TITLE
Notify to service

### PR DESCRIPTION
**Pull request by theosotr**
Add the `subscribe` primitive so that the changes to the init script file are propagated to the state of the system.

### CODE REVIEW

**Comment by alex-harvey-z3q** [comment]
Hi @theosotr, you probably want `notify` here rather than `subscribe` don't you? Also, did you run into an issue where you needed the service to refresh?

**Comment by theosotr** [comment]
@alexharv074, thank you for your reply.

Oops, yes I meant `notify`.  I fixed it.

A modification of the init script should refresh the service so that the new settings are propagated to the system. Otherwise, this might break things in future changes.

**Comment by alex-harvey-z3q** [comment]
Great thanks for your patch @theosotr

**Comment by alex-harvey-z3q** [comment]
Also I just did a release of version 1.4.1 with your patch in it.

**Comment by theosotr** [comment]
Great, thank you!

**Pull request merged**
