### PR TITLE
add support for RHEL/CentOS 8

### PR DESCRIPTION
**Pull request by fraenki**
...please also release a new version to Puppet Forge after merging this change. Thanks :)

### CODE REVIEW

**Comment by alex-harvey-z3q** [comment]
Sure @fraenki ! Give me a bit.

**Comment by alex-harvey-z3q** [comment]
Do you have an example RHEL 8 facts output for
```
      'os' => {'family' => 'RedHat', 'release' => {'major' => '7', 'minor' => '1', 'full' => '7.1.1503'}},
```

**Comment by alex-harvey-z3q** [comment]
@fraenki  ok, version 1.5.0 is released. Thanks for your patch!

**Comment by TheLocehiliosan** [comment]
@alexharv074 - There is no commit tagged as 1.5.0. I wasn't able to see there was a new released version without digging through the issues and PRs.

**Pull request merged**
